cc_library(
    name = "executor",
    srcs = [
        "executor.cpp",
    ],
    hdrs = [
        "executor.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/functional:any_invocable",
    ]
)
