cc_library(
    name = "input_memory",
    srcs = ["input_memory.cpp"],
    hdrs = ["input_memory.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//lib/cpp/io:input",
        "@com_google_absl//absl/base:core_headers",
        "@com_google_absl//absl/status:status",
        "@com_google_absl//absl/status:statusor",
    ]
)

