cc_test(
    name = "singleton_benchmark",
    srcs = ["singleton_benchmark.cpp"],
    deps = [
        "//lib/cpp/singleton:singleton",
        "@com_github_google_benchmark//:benchmark_main",
    ],
)

