cc_library(
    name = "start_stop",
    srcs = [
        "start_stop.cpp",
        "state.cpp",
    ],
    hdrs = [
        "start_stop.h",
        "state.h"
    ],
    visibility = ["//visibility:public"],
)
